import { db } from './firebase';
import { collection, addDoc } from 'firebase/firestore';

const DEMO_USERS = [
  {
    fullName: 'Sooraj Kumar',
    email: 'sooraj@email.com',
    phone: '9876543210',
    plan: 'Monthly Half-day',
    slot: '9am-3pm',
    startDate: '2026-06-26',
    amount: 700,
    paymentMethod: 'upi',
    paymentStatus: 'verified',
    verified: true,
  },
  {
    fullName: 'Priya Sharma',
    email: 'priya@email.com',
    phone: '9876543211',
    plan: 'Monthly Full-day',
    slot: '9am-9pm',
    startDate: '2026-06-25',
    amount: 1200,
    paymentMethod: 'cash',
    paymentStatus: 'verified',
    verified: true,
  },
  {
    fullName: 'Raj Patel',
    email: 'raj@email.com',
    phone: '9876543212',
    plan: 'Quarterly Half-day',
    slot: '3pm-9pm',
    startDate: '2026-06-24',
    amount: 1700,
    paymentMethod: 'upi',
    paymentStatus: 'pending',
    verified: false,
  },
  {
    fullName: 'Anjali Singh',
    email: 'anjali@email.com',
    phone: '9876543213',
    plan: 'Monthly Half-day',
    slot: '9am-3pm',
    startDate: '2026-06-23',
    amount: 700,
    paymentMethod: 'upi',
    paymentStatus: 'verified',
    verified: true,
  },
  {
    fullName: 'Vikram Gupta',
    email: 'vikram@email.com',
    phone: '9876543214',
    plan: 'Quarterly Full-day',
    slot: '9am-9pm',
    startDate: '2026-06-22',
    amount: 3200,
    paymentMethod: 'cash',
    paymentStatus: 'verified',
    verified: true,
  },
  {
    fullName: 'Neha Desai',
    email: 'neha@email.com',
    phone: '9876543215',
    plan: 'Half-yearly Half-day',
    slot: '3pm-9pm',
    startDate: '2026-06-21',
    amount: 3200,
    paymentMethod: 'upi',
    paymentStatus: 'pending',
    verified: false,
  },
  {
    fullName: 'Arjun Reddy',
    email: 'arjun@email.com',
    phone: '9876543216',
    plan: 'Monthly Half-day',
    slot: '9am-3pm',
    startDate: '2026-06-20',
    amount: 700,
    paymentMethod: 'upi',
    paymentStatus: 'verified',
    verified: true,
  },
  {
    fullName: 'Pooja Nair',
    email: 'pooja@email.com',
    phone: '9876543217',
    plan: 'Yearly Full-day',
    slot: '9am-9pm',
    startDate: '2026-06-19',
    amount: 10000,
    paymentMethod: 'cash',
    paymentStatus: 'verified',
    verified: true,
  },
  {
    fullName: 'Rohan Verma',
    email: 'rohan@email.com',
    phone: '9876543218',
    plan: 'Monthly Half-day',
    slot: '3pm-9pm',
    startDate: '2026-06-18',
    amount: 700,
    paymentMethod: 'upi',
    paymentStatus: 'pending',
    verified: false,
  },
  {
    fullName: 'Divya Kapoor',
    email: 'divya@email.com',
    phone: '9876543219',
    plan: 'Quarterly Half-day',
    slot: '9am-3pm',
    startDate: '2026-06-17',
    amount: 1700,
    paymentMethod: 'upi',
    paymentStatus: 'verified',
    verified: true,
  },
  {
    fullName: 'Aditya Joshi',
    email: 'aditya@email.com',
    phone: '9876543220',
    plan: 'Monthly Full-day',
    slot: '9am-9pm',
    startDate: '2026-06-16',
    amount: 1200,
    paymentMethod: 'cash',
    paymentStatus: 'verified',
    verified: true,
  },
  {
    fullName: 'Sneha Mishra',
    email: 'sneha@email.com',
    phone: '9876543221',
    plan: 'Half-yearly Full-day',
    slot: '3pm-9pm',
    startDate: '2026-06-15',
    amount: 6000,
    paymentMethod: 'upi',
    paymentStatus: 'pending',
    verified: false,
  },
  {
    fullName: 'Ravi Kumar',
    email: 'ravi@email.com',
    phone: '9876543222',
    plan: 'Monthly Half-day',
    slot: '9am-3pm',
    startDate: '2026-06-14',
    amount: 700,
    paymentMethod: 'upi',
    paymentStatus: 'verified',
    verified: true,
  },
  {
    fullName: 'Sakshi Pandey',
    email: 'sakshi@email.com',
    phone: '9876543223',
    plan: 'Quarterly Full-day',
    slot: '9am-9pm',
    startDate: '2026-06-13',
    amount: 3200,
    paymentMethod: 'cash',
    paymentStatus: 'verified',
    verified: true,
  },
  {
    fullName: 'Manish Singh',
    email: 'manish@email.com',
    phone: '9876543224',
    plan: 'Monthly Half-day',
    slot: '3pm-9pm',
    startDate: '2026-06-12',
    amount: 700,
    paymentMethod: 'upi',
    paymentStatus: 'pending',
    verified: false,
  },
  {
    fullName: 'Isha Rao',
    email: 'isha@email.com',
    phone: '9876543225',
    plan: 'Monthly Full-day',
    slot: '9am-9pm',
    startDate: '2026-06-11',
    amount: 1200,
    paymentMethod: 'upi',
    paymentStatus: 'verified',
    verified: true,
  },
  {
    fullName: 'Harsh Malhotra',
    email: 'harsh@email.com',
    phone: '9876543226',
    plan: 'Yearly Half-day',
    slot: '9am-3pm',
    startDate: '2026-06-10',
    amount: 6000,
    paymentMethod: 'cash',
    paymentStatus: 'verified',
    verified: true,
  },
  {
    fullName: 'Megha Tiwari',
    email: 'megha@email.com',
    phone: '9876543227',
    plan: 'Quarterly Half-day',
    slot: '3pm-9pm',
    startDate: '2026-06-09',
    amount: 1700,
    paymentMethod: 'upi',
    paymentStatus: 'pending',
    verified: false,
  },
  {
    fullName: 'Nikhil Bhat',
    email: 'nikhil@email.com',
    phone: '9876543228',
    plan: 'Monthly Half-day',
    slot: '9am-3pm',
    startDate: '2026-06-08',
    amount: 700,
    paymentMethod: 'upi',
    paymentStatus: 'verified',
    verified: true,
  },
  {
    fullName: 'Richa Sharma',
    email: 'richa@email.com',
    phone: '9876543229',
    plan: 'Half-yearly Half-day',
    slot: '9am-9pm',
    startDate: '2026-06-07',
    amount: 3200,
    paymentMethod: 'cash',
    paymentStatus: 'verified',
    verified: true,
  },
  {
    fullName: 'Deepak Negi',
    email: 'deepak@email.com',
    phone: '9876543230',
    plan: 'Monthly Full-day',
    slot: '3pm-9pm',
    startDate: '2026-06-06',
    amount: 1200,
    paymentMethod: 'upi',
    paymentStatus: 'pending',
    verified: false,
  },
  {
    fullName: 'Ananya Chatterjee',
    email: 'ananya@email.com',
    phone: '9876543231',
    plan: 'Quarterly Half-day',
    slot: '9am-3pm',
    startDate: '2026-06-05',
    amount: 1700,
    paymentMethod: 'upi',
    paymentStatus: 'verified',
    verified: true,
  },
  {
    fullName: 'Sameer Khan',
    email: 'sameer@email.com',
    phone: '9876543232',
    plan: 'Monthly Half-day',
    slot: '9am-9pm',
    startDate: '2026-06-04',
    amount: 700,
    paymentMethod: 'cash',
    paymentStatus: 'verified',
    verified: true,
  },
  {
    fullName: 'Tanya Mishra',
    email: 'tanya@email.com',
    phone: '9876543233',
    plan: 'Yearly Full-day',
    slot: '3pm-9pm',
    startDate: '2026-06-03',
    amount: 10000,
    paymentMethod: 'upi',
    paymentStatus: 'pending',
    verified: false,
  },
  {
    fullName: 'Vishal Kumar',
    email: 'vishal@email.com',
    phone: '9876543234',
    plan: 'Monthly Half-day',
    slot: '9am-3pm',
    startDate: '2026-06-02',
    amount: 700,
    paymentMethod: 'upi',
    paymentStatus: 'verified',
    verified: true,
  },
  {
    fullName: 'Kavya Singh',
    email: 'kavya@email.com',
    phone: '9876543235',
    plan: 'Half-yearly Full-day',
    slot: '9am-9pm',
    startDate: '2026-06-01',
    amount: 6000,
    paymentMethod: 'cash',
    paymentStatus: 'verified',
    verified: true,
  },
  {
    fullName: 'Aryan Patel',
    email: 'aryan@email.com',
    phone: '9876543236',
    plan: 'Quarterly Half-day',
    slot: '3pm-9pm',
    startDate: '2026-05-31',
    amount: 1700,
    paymentMethod: 'upi',
    paymentStatus: 'pending',
    verified: false,
  },
  {
    fullName: 'Zara Desai',
    email: 'zara@email.com',
    phone: '9876543237',
    plan: 'Monthly Full-day',
    slot: '9am-3pm',
    startDate: '2026-05-30',
    amount: 1200,
    paymentMethod: 'upi',
    paymentStatus: 'verified',
    verified: true,
  },
];

export async function addDemoData() {
  try {
    console.log('Adding demo data...');
    for (const user of DEMO_USERS) {
      const docRef = await addDoc(collection(db, 'members'), {
        ...user,
        id: `ABD${Math.random().toString(36).substr(2, 9).toUpperCase()}`,
        createdAt: new Date().toISOString(),
      });
      console.log(`Added: ${user.fullName} (${docRef.id})`);
    }
    console.log('✅ All demo data added successfully!');
    alert(`✅ Added ${DEMO_USERS.length} demo users!`);
  } catch (error) {
    console.error('Error adding demo data:', error);
    alert('❌ Error adding demo data');
  }
}

// Run this in browser console:
// import { addDemoData } from './demo-data';
// addDemoData();
